version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - taskmanager-network
  
  frontend:
    build: ./frontend
    ports: 
      - "80:80"
    depends_on:
      - backend
    networks:
      - taskmanager-network

networks:
  taskmanager-network:
    driver: bridge